### ISSUE TITLE
Page redirects to front-end after you save settings

### ISSUE THREAD

**Issue by jasdeepm13** [Florent73/send-pdf-for-contact-form-7#12]
I am using verion 0.8
when I click on save settings, the page redirects to front end of the website saying : 

> 404
> Page cannot be found !

However, the url remains the same as : `https://www.myweb.....com/wp-admin/admin.php?page=wpcf7-send-pdf`
This is really strange, this started happening right after after I updated the plugin.

Can you please fix this as soon as possible.
Thank you!

**Comment by Florent73** [comment]
Hi!
Have you the last version?

Thanks
