### ISSUE TITLE
404 - PDF Fails to Load for Anonymous Users

### ISSUE THREAD

**Issue by svetek** [Florent73/send-pdf-for-contact-form-7#14]
Hello. Great plugin! However, we are experiencing a problem, when PDF is sent successfully via email, but is not shown to the end user in a browser when user is not authenticated. 
Here is a bit for authenticated user:
document.addEventListener( 'wpcf7mailsent', function( event ) {
/* REDICTION DIRECT */
if ( '300' === event.detail.contactFormId ) {
var location = 'http://tempstaging.wpengine.com/wp-content/uploads/2020/10/Print1--5f9069692ff94.pdf'; window.open(location, '_self');}
}, false );
Not authenticated:
document.addEventListener( 'wpcf7mailsent', function( event ) {
/* REDICTION DIRECT */
if ( '300' === event.detail.contactFormId ) {
var location = 'http://tempstaging.wpengine.com/wp-content/uploads/2020/10/Print1--.pdf'; window.open(location, '_self');}
}, false );
**********
The above bits are from the page before user hist "generate PDF" button on the form. The results are
1. For authenticated user - form is displayed in the browser and delivered by mail
2. For anonymous user - 404 error in the browser, but delivered by mail
Please advise.

**Comment by Florent73** [comment]
Hi!

Thanks for your report.

I check it on my website : https://madeby.restezconnectes.fr/project/send-pdf-for-contact-form-7/

I'm not logged and i have the COOKIE ID : 
document.addEventListener( 'wpcf7mailsent', function( event ) {
            /* REDIRECTION  */
        if ( "144" === event.detail.contactFormId) { location.replace("https://madeby.restezconnectes.fr/merci-send-pdf-for-cf7/?pdf-reference=5f91a6959ddea");}
}, false );

Thanks for your response.

**Comment by Florent73** [comment]
Hi!

I solved the bug, can you download and test the last version?

Thanks

**Comment by svetek** [comment]
> Hi!
> 
> I solved the bug, can you download and test the last version?
> 
> Thanks
Lovely! Will give it a try and let you know.

**Comment by AlexSkyBrain** [comment]
Hi!
Have the same problem. Plugin update in WordPress did not work, still 404 error (

**Comment by Florent73** [comment]
Hi!
You have download from GitHub version or updating from WP?

Thanks

**Comment by AlexSkyBrain** [comment]
Update from WP. Should i try a git version ?

**Comment by AlexSkyBrain** [comment]
Im try a git version but the same -  https://prnt.sc/v7thsn

**Comment by Florent73** [comment]
Hi!

Can you try to change the folder by default, with the specific option in my plugin ?

Thanks

**Comment by Florent73** [comment]
Hi!

I moved the code for delete COOKIE for regenerating it.

Can you testing that?

Thanks

**Comment by AlexSkyBrain** [comment]
Hi, this is site url -  http://ringaidstaging.wpengine.com/
Click om  Donate button and  form appears.
From now reference dont work simetimes. Cookies empty

**Comment by svetek** [comment]
Clearly document ID gets lost somehow. Would putting a document ID in a global variable be helpful?

**Comment by Florent73** [comment]
Hi!

I would try it!

Thanks

**Comment by svetek** [comment]
Are you suggesting we fork it? Also, what would be your next step?

**Comment by Florent73** [comment]
Yes you can try it for me!

Thanks

**Comment by AlexSkyBrain** [comment]
The one thing that helps is change all $_COOKIE['pdf_uniqueid'] to $_SESSION['YOUR_VAR']
Thanks

**Comment by Florent73** [comment]
Thanks. Older versions had this.

I try to change it.

**Comment by Florent73** [comment]
In fact the problem is that the sending is done in AJAX and the javascript code to redirect to the PDF after sending is not updated, so the ID does not change.

**Comment by Florent73** [comment]
Ok, this actual version 0.8.4 are now in SESSION.

I have removed the ID in the redirect code after sending form. Also, i removed the button option to download PDF with shortcode (because it not working correctly).

Hope to help all of you!
