### ISSUE TITLE
Hide empty fields / Conditional tags

### ISSUE THREAD

**Issue by wrapper** [Florent73/send-pdf-for-contact-form-7#15]
Hi there

Is there any plan to implement a way to hide fields that are empty or use conditional tags in the plugin?

Thanks

**Comment by Florent73** [comment]
Hi,

What extension do you use for conditional tags?

Thanks

**Comment by Florent73** [comment]
Hi!

My plugin is now compatible with "CF7 conditional fields" and "CF7 conditional fields PRO"

Thanks
