### ISSUE TITLE
shortcode is not working 

### ISSUE THREAD

**Issue by ramesh3828** [Florent73/send-pdf-for-contact-form-7#16]
the shortcode is not working [wpcf7pdf_download]

**Comment by thomasfrobieter** [comment]
Same here, placed it in the success message, it ain't replaced.

**Comment by Mwamitovi** [comment]
@Florent73 same issue with me as @thomasfrobieter when used a "redirect page". 
Any ideas on how we could troubleshoot it?

**Comment by Florent73** [comment]
Hi!

Yes, i removing this shortcode because it don't works well.

Thanks
