### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tjlabais** [Florent73/send-pdf-for-contact-form-7#17]
It would be nice to include pdf file restriction options (restrict to print and fill-forms); so signatures in signed contract will be protected. This feature is already included in mpdf, just need to implement in send-pdf.

code as follows will only allow to print, fill forms, and read the pdf, but modification, copying, extracting, etc is password protected
`$mpdf->SetProtection(array('print','fill-forms'), '', $pdfPassword, 128);`

Thanks for a great plugin

**Comment by Florent73** [comment]
Hi!

I updated the send-pdf.php file

Thanks

**Comment by tjlabais** [comment]
Great. Thanks!
