### ISSUE TITLE
"Other files to attach" does not work

### ISSUE THREAD

**Issue by mmkwip** [Florent73/send-pdf-for-contact-form-7#18]
The "other file to attach" part does not work. I put a url type "https://" with a .pdf

**Comment by Florent73** [comment]
Hi!

Try to enter your PDF URL file like : http://... not https://

Thanks

**Comment by mmkwip** [comment]
Hi!

Same, but with error notice : 
**Notice**: Undefined offset: 0 in **/home/lrzh9571/public_html/wp-content/plugins/send-pdf-for-contact-form-7/views/send-pdf-admin.php** on line **431**

**Comment by Florent73** [comment]
Hi!

Please, download the lastest version and try again.

Thanks to your report...
