### ISSUE TITLE
SESSIONS alternative?

### ISSUE THREAD

**Issue by timostsauber** [Florent73/send-pdf-for-contact-form-7#20]
Great plugin!   Although the usage of SESSIONS is not desirable, as it is no longer supported by WordPress or many hosting platforms, since it breaks caching.  WordPress itself no longer uses SESSIONS, either do most other up to date plugins.

Do you have any plans in your roadmap to replace PHP SESSIONS with something more compatible with WordPress and modern hosting solutions?  It would be very awesome if you did!

Thanks!

**Comment by Florent73** [comment]
Hi!

Yes i hope to change the usage of SESSIONS soon as possible.

I works on a another solution... some ideas?

Thanks

**Comment by Florent73** [comment]
Hi!

For the lastest verion, I removed usage SESSIONS, I use TRANSIENT instead

Does it work for you?

**Comment by proteinone** [comment]
Hi @Florent73 !

Thats amazing : )

I agree that TRANSIENTS are probably the best option to replace SESSIONS in WordPress, as they can be used for both guest and logged in users, and will still work normally if the webhost has disabled PHP SESSIONS.

I'll download this new version and test asap and give feedback.

Cheers,

**Comment by Florent73** [comment]
Hi!

Thanks...

Your feedback?
