### ISSUE TITLE
[reference] same IDs error

### ISSUE THREAD

**Issue by p0se** [Florent73/send-pdf-for-contact-form-7#22]
I use the [reference] function. 
When generating the PDF files, unique IDs or names are not always generated. 
I have several files with the same name. This leads to overwriting the PDF files. 

![1](https://user-images.githubusercontent.com/19638022/141780271-0aafabd0-6f2d-4a92-9cb3-9dac1d8c2744.PNG)
![2](https://user-images.githubusercontent.com/19638022/141780280-32021e3f-375a-4e3d-b677-2d4b4c86864d.PNG)
![3](https://user-images.githubusercontent.com/19638022/141780284-5277ac59-f74a-482d-bc12-beb2ba08c985.PNG)

**Comment by timostsauber** [comment]
This is possibly related to the other issue [https://github.com/Florent73/send-pdf-for-contact-form-7/issues/21](https://github.com/Florent73/send-pdf-for-contact-form-7/issues/21)

i.e. the unique ID (sessions) are being cached

**Comment by Florent73** [comment]
Hi!

For the lastest verion, I removed usage SESSIONS, I use TRANSIENT instead

Does it work for you?
