### ISSUE TITLE
file not attached when seconds added to [date]

### ISSUE THREAD

**Issue by Reghyz** [Florent73/send-pdf-for-contact-form-7#23]
if i use this format  :  YmdHis   i see the correct "timestamp" right to the date format input field it in admin after saving the changes, 
but when submitting the mail no pdf is attached to the mail (it works with the default one set as "dmY"). 
I can see that the pdf file has been generated with the correct name.

( i wanted to try using date with  U ou YmdHis format to obtain uniques filenames to circumvent the caching session ID problem )

**Comment by Reghyz** [comment]
oh, i think i understand whats wrong,  it works but wpcf7pdf_name_pdf() is called at differents places to retrieve the filename, with [date] formated with second in the name calculated inside it will never returns two time the same filename

**Comment by Florent73** [comment]
Hi!

Where is called with [date]?

I don't see that!

Thanks

**Comment by Florent73** [comment]
Hi!

Thanks to try the lastest version. The bug is fixed.

Thanks
