### ISSUE TITLE
timeout after config import

### ISSUE THREAD

**Issue by matbr** [Florent73/send-pdf-for-contact-form-7#24]
Hi team, 

after moving a pdf config from another server send pdf runs into tiemout. I assume included files attachments, that are not available on the new server might cause this isuues. 

Where do I find the config for a form to delete this and re-import after fixing the attachment links in the json?

best, 

Mat

**Comment by Florent73** [comment]
Hi!

Yes, attachement are not included in json file export...

Thanks
