### ISSUE TITLE
version 0.9.2 - No PDF are send a attachement

### ISSUE THREAD

**Issue by MHolkamp** [Florent73/send-pdf-for-contact-form-7#25]
Until 0.9.1 everything was working fine.
With the update to 0.9.2 no PDF where send as attachment anymore.
I had to rollback to the old version.
Is this a common issue?

**Comment by Florent73** [comment]
Hi!
I had to secure the plugin even more.
So, I'm working on it!

Thanks

**Comment by MHolkamp** [comment]
HI,

It seems to be solved in version 0.9.3.
Thanks!
Keep up the good work

**Comment by Florent73** [comment]
Thanks
