### ISSUE TITLE
HTML attributes removed after saving

### ISSUE THREAD

**Issue by tjlabais** [Florent73/send-pdf-for-contact-form-7#28]
table  td colspan attribute could not be save.

**Comment by tjlabais** [comment]
changing <div id="id-pic"> into <div class="sub_id_pic">; also changing #id-pic to .sub_id_pic fixed the issue.

**Comment by tjlabais** [comment]
having explicit declaration of width per table td causes the table to have unexpected results
`<table><tbody>
<tr>
<td style="width:50%"><td><td style="width:50%"><td>
<td style="width:50%"><td><td style="width:50%"><td>
<td style="width:50%"><td><td style="width:50%"><td>
<td style="width:50%"><td><td style="width:50%"><td>
</tr>
</tbody></table>`
the code above produces a 70% first column and 30% second column output

**Comment by Florent73** [comment]
Hi!

Try the lastest version, it's ok now!

Thanks
