### ISSUE TITLE
Problems with Cyrillic in checkboxes and radio buttons

### ISSUE THREAD

**Issue by jon4god** [Florent73/send-pdf-for-contact-form-7#29]
When Cyrillic is used, the values are not inserted into the pdf file.

[radio vv-english use_label_element default:1 "Бaзoвый" "Разговорный" "Свободное владение" "Владею в совершенстве"]

[radio vv-agreement use_label_element default:1 "Да" "Нет"]

[checkbox* vv-position use_label_element "Наставник" "Помощник наставника" "Носитель английского" "Спортивный инструктор" "Ведущий собраний" "Участник медиа-команды"]

**Comment by jon4god** [comment]
It's the same problem with Japanese.

**Comment by Florent73** [comment]
Hi!

Can you donwload and relplace plugin by the lastest version?

Thanks
