### ISSUE TITLE
Image not attached on pdf file

### ISSUE THREAD

**Issue by biju001** [Florent73/send-pdf-for-contact-form-7#3]
This is very helpful plugins, but I am facing some issue. I saw many other people also facing similar issues. I installed 0.6.9 version from Wordpress site and installed  .7 versions also both are the same issue. Pdf file, send to mail, but inside pdf file image is missing. It shows (X) symbol. 

Image is show in email body when i change [fil]e tag to [url-file] but not in pdf. i think this is pdf generate image url issue.

Can see this issue please.

**Comment by Florent73** [comment]
Hi!

Can you testing again with the last version?

Thanks
