### ISSUE TITLE
No admite la propiedad valign en las td de las tablas

### ISSUE THREAD

**Issue by androot-dev** [Florent73/send-pdf-for-contact-form-7#31]
No admite la propiedad valign en las td de las tablas

**Comment by Florent73** [comment]
Hi!

Thanks to download again. I have fix it!

see you

**Comment by androot-dev** [comment]
Hi, podria decirme como lo actualizo para poder usar la propiedad valign
sin que se pierdan mis formularios?

**Comment by Florent73** [comment]
Hi,

Just download the GitHib zip file. Adding a New plugin and replace by my GitHub version.
