### ISSUE TITLE
Attach Image on PDF: Incorrect orientation ⬅️ ⬆️ ➡️

### ISSUE THREAD

**Issue by Cm-8** [Florent73/send-pdf-for-contact-form-7#36]
Hi to all,

I created a form where the smartphone user must attach a photo of himself taken at the moment.
Everything works, I can insert the image in the generated pdf and send it by mail.

However, the orientation of the image is wrong.
Try to explain:
- if I insert the image as an attachment to the email from CF7, the image is oriented correctly ⬆️.
- if I insert the image in the pdf, the image is rotated 90° counterclockwise ⬅️ (as if it loses the information of where is the top).

The curious thing is that:
- from an iPhone the orientation is 90° counterclockwise ⬅️ , while 
- from an Android it is 90° clockwise ➡️

Is it possible to maintain or manage orientation?

Thanks

**Comment by Florent73** [comment]
Hi!

What is the plugin used for photo of himself taken?

Thanks

**Comment by Florent73** [comment]
Ok

I'm working on it!

Thanks

**Comment by Florent73** [comment]
Hi!

Can you testing again? I think it's fixed!

Thanks

**Comment by Cm-8** [comment]
Tried 0.9.9.4
It works!!
