### ISSUE TITLE
text rotate not working in pdf, can u please suggest how to rotate

### ISSUE THREAD

**Issue by deraaj85** [Florent73/send-pdf-for-contact-form-7#37]
text rotate not working in wpcf7pdf, can u please suggest how to rotate

**Comment by Florent73** [comment]
Hi!

This is ok now!

Thanks

**Comment by restezconnectes** [comment]
Hi!

See this : https://github.com/mpdf/mpdf-examples/blob/development/example05_tables.php#L836

It's working
