### ISSUE TITLE
Image not attached on pdf file 6/8/2023

### ISSUE THREAD

**Issue by HHNghia28** [Florent73/send-pdf-for-contact-form-7#38]

**Comment by HHNghia28** [comment]
Hello,
i am using your plugin it is great but i am having problem that the image is not attached on the pdf file

**Comment by Florent73** [comment]
Hi!

Are you in local mode, or temporaly URL?

Thanks

**Comment by HHNghia28** [comment]
Hi!

I remember at that time I tested with localhost.

Thanks
