### ISSUE TITLE
Bug in radio selection

### ISSUE THREAD

**Issue by swaan** [Florent73/send-pdf-for-contact-form-7#39]
When I create a radio [radio test "Very good" "good"]
and select "Very good" CF7 prints [test] as 'Very good' but PDF prints [test] as 'Very good good' 

I don't know if related but the radio results also come with an extra space at the end like 'Very good' -> 'Very good '

**Comment by Florent73** [comment]
Hi!

This bug is now fixed! (only GitHub version)

Thanks
