### ISSUE TITLE
add stylesheet for pdf

### ISSUE THREAD

**Issue by gluehbirne123** [Florent73/send-pdf-for-contact-form-7#4]
Hi, nice plugin so far.

But i cannot figure out how to add a styleesheet. there is a textbox - should i put there a url or how does this work?

**Comment by Florent73** [comment]
Hi!

Thanks for using my plugin.

Just uploading your file and adding the link in the input "Add a CSS file".

It's working for you?

**Comment by gluehbirne123** [comment]
Hi @Florent73 , it is working. Thanks. Maybe a tooltip or something else would be helpful for other users :-)

Thanks!
