### ISSUE TITLE
No support for Cyrillic

### ISSUE THREAD

**Issue by kirichme** [Florent73/send-pdf-for-contact-form-7#40]
Hi, there is no support for Cyrillic Time New roman Bulgarian, if possible, please add in the next updates. Thanks!

[times-new-roman-cyr.zip](https://github.com/Florent73/send-pdf-for-contact-form-7/files/12413354/times-new-roman-cyr.zip)

**Comment by Florent73** [comment]
Hi!

Download and install the last version on GitHub. I've adding Cyrillic Time New roman Bulgarian font.

Thanks

**Comment by kirichme** [comment]
Thanks!
