### ISSUE TITLE
checkbox not working with some characters

### ISSUE THREAD

**Issue by fabiankopatschek** [Florent73/send-pdf-for-contact-form-7#42]
Hi,
first of all thank you for your great plugin.

While using the checkboxes i found out, that the pdf does not contain the checked boxes if i'm using some characters. So far it seems, that this happens with dots. But i can not rule out, that this won't happen with other characters too.

Here is a minimal code snippet for reproducing it:

Formular:
---
[checkbox checkbox-a "A"]

[checkbox checkbox-b "...B"]

[checkbox checkbox-c "C."]

[submit "Send"]

---

Create Pdf:
---

<p>
   [checkbox-a]
</p>
<p>
   [checkbox-b]
</p>
<p>
   [checkbox-c]
</p>

---

In this case b and c will not be checked in the pdf.

Regards
Fabian

**Comment by Florent73** [comment]
Hi!

Can you testing the lastest version?

Thanks
