### ISSUE TITLE
Render custom shortcodes

### ISSUE THREAD

**Issue by btxtiger** [Florent73/send-pdf-for-contact-form-7#43]
I am using the WP Plugin "Shortcoder" to create reusable long texts, that I want to embed in the PDF.

`[sc name="very_long_text"][/sc]`

However it does not get rendered.

**Comment by Florent73** [comment]
Hi!

Can you testing with my lastest version.

So, enter [very_long_text] in the "Enter here your Shortcodes" setting, not the entire shortcode from Shortcoder plugin.

Thanks

**Comment by btxtiger** [comment]
@Florent73 Sorry for my late reply. I tested it, but unfortunately it seems not to work.

![image](https://github.com/Florent73/send-pdf-for-contact-form-7/assets/15804690/6927bad3-199b-4ef9-81ac-91e9f4eeeb24)
![image](https://github.com/Florent73/send-pdf-for-contact-form-7/assets/15804690/07399814-8fb4-4275-b163-bd0bee520eab)
![image](https://github.com/Florent73/send-pdf-for-contact-form-7/assets/15804690/7dab57ae-9361-4b14-9a76-8b34fb34d4ed)


Also recently, the [datepicker formatting shortcodes](https://contactform7.com/date-field/#Format_Date_Value_in_Mail) from CF7 are not working anymore:
```
[_format_your-date "D, d M y"]
```

![image](https://github.com/Florent73/send-pdf-for-contact-form-7/assets/15804690/1e4c33e5-0f9f-40eb-9526-ba7d47d3a62f)

**Comment by btxtiger** [comment]
Thank you, this worked!
