### ISSUE TITLE
Email to those who fill out the form?

### ISSUE THREAD

**Issue by LionBeq** [Florent73/send-pdf-for-contact-form-7#45]
Hello,

There is an option to send an e-mail to those who fill out the form, but the plugin does not know where to find the e-mail? There should be an area where we can add the e-mail field with a short code. I would be happy if there is a solution to this issue.

**Comment by Florent73** [comment]
Hi!

Yes, the PDF is sending at recipient who is fill the form.

There is a option for sending at sender (config CF7 mail 1) or recipient (config CF7 mail 2) or both!

Does this meet your request?

Thanks
