### ISSUE TITLE
Error image in PDF

### ISSUE THREAD

**Issue by Carorodriguezdmgz** [Florent73/send-pdf-for-contact-form-7#46]
Hello. Please help us. Firstly, thank you for this plugin; it has been a tremendous help to our church. However, it is causing the following issues:

- The PDF arrives attached to the email, but instead of displaying the photo as it used to, it now shows a black circle.

- The photo is not being saved in the server path.

We have tried various solutions, including deactivating all plugins and leaving only the essential ones active. We've also removed the cache plugins, but nothing seems to resolve the problem.

I have attached a PDF for your reference. We hope you can assist us.

Thank you very much.
[document-pdf-653f0d921d9e1.pdf](https://github.com/Florent73/send-pdf-for-contact-form-7/files/13209461/document-pdf-653f0d921d9e1.pdf)

**Comment by Florent73** [comment]
Hi!

I'm working on it!

Thanks

**Comment by Carorodriguezdmgz** [comment]
> Hi!
> 
> I'm working on it!
> 
> Thanks

**Comment by Carorodriguezdmgz** [comment]
> Hi!
> 
> I'm working on it!
> 
> Thanks



> ¡Hola!
> 
> ¡Estoy trabajando en ello!
> 
> Gracias

Thank You Florent :)
