### ISSUE TITLE
Page Redirection

### ISSUE THREAD

**Issue by palafix** [Florent73/send-pdf-for-contact-form-7#47]
Page Redirection not working for me anymore in the new version.

**Comment by palafix** [comment]
Page Redirection still not working in the major update.

I dont know if this is related.
Uncaught ReferenceError: fieldname is not defined
    at HTMLDocument.<anonymous> (declaratieformulier/?pdf-reference=6546641b50ec2:1353:34)
    at a (index.js?ver=5.8.1:1:782)
    at index.js?ver=5.8.1:1:6563

is ther a way to fix it because my clients needs to download the pdf and i dont know a quick fix for it.

Im using Version 1.0.1.0

**Comment by Florent73** [comment]
Hi!

Have you testing the new version here : [([https://demo.restezconnectes.fr/send-pdf-for-contact-form-7/](https://demo.restezconnectes.fr/send-pdf-for-contact-form-7/))

It's working on my website demo!

Thanks

**Comment by Florent73** [comment]
Do you use form tags for the PDF name?

**Comment by palafix** [comment]
Yes i have tested the demo.
No i use just a name for the pdf file

**Comment by palafix** [comment]
Hey,

Now i get this:
index.js?ver=5.8.1:1 
POST https://www.palafix.nl/wp-json/contact-form-7/v1/contact-forms/460/feedback 500 (Internal Server Error).

If i disable youre plugin its gone.
I removed the plugin and installed back and same error

**Comment by Florent73** [comment]
Hi!

I fixed the bug. Can you download the lastest version?

Thanks

**Comment by palafix** [comment]
Hi,

Download and test and work.

The error 500 i fixed, that whas a pdf layout error somehow.
Thank you.

**Comment by palafix** [comment]
See my edited post.

**Comment by palafix** [comment]
Hey,
 
I have installed the 1.0.1.1 and the redirection works good.
Only the error 500 is fixed when i remove the shortcodes, i tested it with [wpcf7pdf_test] but gives also this error.

I have deleted all plugins and put my old backup back to my site and installed the newest 1.0.1.1 but the error 500 is still there when i use the shotcodes.

I have made a workarround to use my forms but it's not a nice solution

**Comment by palafix** [comment]
Thanks, it's working now.

I have 1 questen, i have a form for declarations so they must upload a img.
I use Conditional Fields for Contact Form 7 to open a new row if the client wants to put another declaration.
But if they only put 1 and send the pdf the rows are visible in the pdf and the images that are not uploaded are a black triangle.
Is it posible to make the rows that are not filled invisible in the pdf.

I hope you understand what i mean.
