### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Carorodriguezdmgz** [Florent73/send-pdf-for-contact-form-7#48]
Hello Florent,

I'm a bit confused as to why it's marked as completed. Could you please guide me on how to resolve this error in the PDF? Thank you.

Hi!

I'm working on it!

Thanks

_Originally posted by @Florent73 in https://github.com/Florent73/send-pdf-for-contact-form-7/issues/46#issuecomment-1787492731_

**Comment by Florent73** [comment]
Hi!

Check and test my new version 1.0.1.0
I've reprogramming some parts and testing in my demo website.

Thanks

**Comment by Carorodriguezdmgz** [comment]
Thank you so much Florent for your help. Is working.
