### ISSUE TITLE
htaccess: Options not allowed here

### ISSUE THREAD

**Issue by Raruto** [Florent73/send-pdf-for-contact-form-7#5]
On shared hosts the following line causes several 500 errors, couldn't we avoid creating the `.htaccess` file? (currently wordpress doesn't allow free access to the upload folder?)

https://github.com/Florent73/send-pdf-for-contact-form-7/blob/642b38d7a7b8f47fd9616753c6e5ad3a40f5b7df/classes/send-pdf.php#L396

**Comment by Florent73** [comment]
Hi!
I remove this line.

Thanks
