### ISSUE TITLE
Cannot edit form after update: Uncaught TypeError: fputcsv()

### ISSUE THREAD

**Issue by lionwolfdev** [Florent73/send-pdf-for-contact-form-7#52]
Hello there,

tried to edit the PDF configuration of a form, but after selecting the form from the dropdown list, an error occurs and I received the following error report by e-mail:

```
Ein Fehler vom Typ E_ERROR wurde in der Zeile 292 der Datei
/redacted/wp-content/plugins/send-pdf-for-contact-form-7/classes/generate.php
verursacht. Fehlermeldung: Uncaught TypeError: fputcsv(): Argument #1 ($stream)
must be of type resource, bool given in
/redacted/wp-content/plugins/send-pdf-for-contact-form-7/classes/generate.php:292
Stack trace:
#0
/redacted/wp-content/plugins/send-pdf-for-contact-form-7/classes/generate.php(292):
fputcsv(false, Array, ',')
#1
/redacted/wp-content/plugins/send-pdf-for-contact-form-7/views/send-pdf-admin.php(301):
WPCF7PDF_generate::wpcf7pdf_create_csv('1234', 'Form name',
'/redacted/w...', 1)
#2
/redacted/wp-content/plugins/send-pdf-for-contact-form-7/classes/send-pdf.php(248):
include('/redacted/w...')
#3 /redacted/wp-includes/class-wp-hook.php(324):
cf7_sendpdf->wpcf7pdf_dashboard_html_page('')
#4 /redacted/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('',
Array)
#5 /redacted/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /redacted/wp-admin/admin.php(259): do_action('formulare_page_...')
#7 {main}
  thrown
```

It worked before, so either it has something to do with the updates or the recent changes I made on the CF7 form itself. I'm using the current plugin version V.1.0.1.3 with Wordpress 6.4.1.

Uninstalling and reinstalling the plugin allows me opening the configuration _once_, but upon saving the configuration the error occurs again. It seems some old data are not removed when uninstalling, so it tries to load the faulty stored data again? I also tried setting "Delete all config for this form?" and "Disable generate CSV file?" to yes, but unfortunately without luck. 

Does the plugin have some sort of "database" where it records the submissions?

Appreciate your suggestions for a workaround. Thank you!

**Comment by Florent73** [comment]
Hi!

This bug is fixed with the 1.0.1.4 version.

Thanks
