### ISSUE TITLE
document.addEventListener  error message

### ISSUE THREAD

**Issue by xabiliza** [Florent73/send-pdf-for-contact-form-7#53]
I have updated to Wordpress 6.4.1 and I have seen that this plugin shows a javascript error after footer in all pages except the page that that contact 7  form exists.
`document.addEventListener( 'wpcf7submit', function( event ) { var reference = Date.now().toString(36) + Math.floor(Math.pow(10, 12) + Math.random() * 9*Math.pow(10, 12)).toString(36); jQuery('input[name="wpcf7cfpdf_hidden_reference"]').val(reference); }, false ); `
any idea to solve this issue?

**Comment by Florent73** [comment]
Hi!

I fixed this bug. Just download files (/classes/ send-pdf.php), no adding a new version.

Thanks

**Comment by ahobitt** [comment]
Hi @Florent73 
Thank you very much for the update. Since it completely destroyed my forms, the update helped a lot. 
Would you like to make a new version for others?

**Comment by Florent73** [comment]
Hi!

Yes, as soon is possible.

Thanks
