### ISSUE TITLE
Multiple date format not working

### ISSUE THREAD

**Issue by jonaaix** [Florent73/send-pdf-for-contact-form-7#56]
I have multiple date inputs in my form. But in the PDF, only the first shortcode gets rendered correctly using 
```
[_format_myDate1 "d.m.Y"] // => 24.11.2023
[_format_myDate2 "d.m.Y"] // => [_format_myDate2 "d.m.Y"]
```
The other ones don't get rendered at all.

**Comment by restezconnectes** [comment]
Hi!

See and test my demo form : [https://demo.restezconnectes.fr/send-pdf-for-contact-form-7-debug-form/](https://demo.restezconnectes.fr/send-pdf-for-contact-form-7-debug-form/)

With:

Date : [date-332]
Date autre format: [_format_date-332 "D, d M y"]

Date 2 : [date-438]
Date autre format: [_format_date-438"d.m.Y"]

Date 3 : [date-506 ]
Date autre format: [_format_date-506 "d-m-Y"]

Thanks
