### ISSUE TITLE
Form submission redirecting to this plugins options page

### ISSUE THREAD

**Issue by SirWoosh** [Florent73/send-pdf-for-contact-form-7#9]
Since the latest update, after submitting a form, when I am already logged in I get redirected to example.com/wp-admin/admin.php?page=wpcf7-send-pdf#wpcf7-f637-p21-o2. If I submit a form as guest user I'm not redirected, but this parameter is added to my current URL: ?login=failed#wpcf7-f637-p21-o2 and there is no confirmation message from Contact Form 7. I hope this is the correct place to tell you about this issue.

**Comment by Florent73** [comment]
Hi!

Yes, it's the correct place.

I look the problem soon. Thanks

**Comment by Florent73** [comment]
Hi!

This bug is now fixed.

Download the file again and try it!

Thanks

**Comment by SirWoosh** [comment]
Hi,

yes the bug is now also fixed for me. Thank you very much

Am So., 30. Aug. 2020 um 14:40 Uhr schrieb Restez Connectés <
notifications@github.com>:
